CREATE SCHEMA clientes_approval_dev;

USE clientes_approval_dev;

CREATE TABLE CLIENTES(
	ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'IDENTIFICADOR PRINCIPAL DEL REGISTRO',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'NOMBRE DEL CLIENTE',
    APATERNO VARCHAR(50) NOT NULL COMMENT 'APELLIDO PATERNO DEL CLIENTE',
    AMATERNO VARCHAR(50) NOT NULL COMMENT 'APELLIDO MATERNO DEL CLIENTE',
    FNACIMIENTO DATE NOT NULL COMMENT 'FECHA DE NACIMIENTO DEL CLIENTE',
    INGRESOSMENSUALES DECIMAL(10,2) NOT NULL COMMENT 'INGRESOS MENSUALES DEL CLIENTE',
    DEPENDIENTESECONOMICOS INT NOT NULL COMMENT 'NUMERO DE DEPENDIENTES ECONOMICOS',
    RFC VARCHAR(13) NOT NULL COMMENT 'REGISTRO FEDERAL DE CONTRIBUYENTES',
	APROBADO CHAR(1) NOT NULL COMMENT 'BOOLEANO PARA SABER SI SE APROBO O NO EL CREDITO'
);


